version: '3.4'

services:
  app:
    ports:
      - 3000:3000
    build:
      context: ./
      dockerfile: ./.docker/Dockerfile
    volumes:
      - ./reads:/reads
    tty: true
    container_name: reads
